@baseUrl = http://localhost:8000

# @name generateToken
POST {{baseUrl}}/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "12345678"
}
###
# Criar uma nova Table
POST {{baseUrl}}/tables HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "New Table",
    "description": "Description da Table",
    "type": "Example type",
    "state": "Example State"
}

###
# Obter todas as Tables
GET {{baseUrl}}/tables HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
# Atualizar uma Table específica
PUT {{baseUrl}}/tables/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "Table Updated",
    "description": "Description Updated",
    "type": "New Type",
    "state": "New State"
}

###
# Deletar uma Table específica
DELETE {{baseUrl}}/tables/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}