@baseUrl = http://localhost:8000

# @name generateToken
POST {{baseUrl}}/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "12345678"
}

###
POST {{baseUrl}}/projects HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "project_2",
    "tenant_name": "tenant_6"
}

###
GET {{baseUrl}}/projects HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
GET {{baseUrl}}/projects/filter?name=project_2 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
GET {{baseUrl}}/projects/filter?id=2 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
PUT {{baseUrl}}/projects/6 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "Project Updated 7"
}

###
DELETE {{baseUrl}}/projects/6 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}