@baseUrl = http://localhost:8000

# @name generateToken
POST {{baseUrl}}/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "12345678"
}

###
POST {{baseUrl}}/tables HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
  "description": "input",
  "name": "input",
  "state": "active",
  "type": "filter"
}

###
GET {{baseUrl}}/tables HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
PUT {{baseUrl}}/tables/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "Table Atualizada",
    "type": "Novo Tipo",
    "state": "Novo Estado"
}

###
DELETE {{baseUrl}}/tables/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
