@baseUrl = http://localhost:8000

# @name generateToken
POST {{baseUrl}}/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "j@j.com",
    "password": "12345678"
}

###
GET {{baseUrl}}/tenants HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
GET {{baseUrl}}/tenants/2 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json


###
GET {{baseUrl}}/tenants/name/tenant_3 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
GET {{baseUrl}}/tenants/filter?name=tenant_3 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

###
GET {{baseUrl}}/tenants/filter?id=1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json


###
POST {{baseUrl}}/tenants HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "tenant_5"
}

###
PUT {{baseUrl}}/tenants/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

{
    "name": "Tenant Updated 2"
}

###
GET {{baseUrl}}/tenants HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}
Content-Type: application/json

@baseUrl = http://localhost:8000

###
DELETE {{baseUrl}}/tenants/1 HTTP/1.1
Authorization: Bearer {{generateToken.response.body.access_token}}